export const SET_TODO_INPUT = 'set_todo_input'
export const ADD_TODO_INPUT = 'add_todo_input'
export const REMOVE_TODO_INPUT = 'remove_todo_input'
export const EDIT_TODO_INPUT = 'edit_todo_input'
export const UPDATE_TODO_INPUT = 'update_todo_input'
